server:
  servlet:
    context-path: /uber
  port: 12345

spring:
  h2:
    console:
      enabled: true
  mvc:
   pathmatch:
     matching-strategy: ANT_PATH_MATCHER
     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName:  org.h2.Driver

    
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    service-name: uber
    http-sender:
      url: ${JAEGAR_URL:http://localhost:80} 