server:
  servlet:
    context-path: /uber
  port: 12345

spring:
  mvc:
   pathmatch:
     matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/uber?currentSchema=public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      schema: init
  cache:
    type: simple

    
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    service-name: uber
    http-sender:
      url: ${JAEGAR_URL:http://localhost:80} 